export interface Country {
  code: string;
  flag: string;
  name_pt: string;
  name_en: string;
  name_es: string;
}

export const COUNTRIES: Country[] = [
  { code: "CN", flag: "🇨🇳", name_pt: "China", name_en: "China", name_es: "China" },
  { code: "US", flag: "🇺🇸", name_pt: "Estados Unidos", name_en: "United States", name_es: "Estados Unidos" },
  { code: "ES", flag: "🇪🇸", name_pt: "Espanha", name_en: "Spain", name_es: "España" },
  { code: "MX", flag: "🇲🇽", name_pt: "México", name_en: "Mexico", name_es: "México" },
  { code: "DE", flag: "🇩🇪", name_pt: "Alemanha", name_en: "Germany", name_es: "Alemania" },
  { code: "IT", flag: "🇮🇹", name_pt: "Itália", name_en: "Italy", name_es: "Italia" },
  { code: "FR", flag: "🇫🇷", name_pt: "França", name_en: "France", name_es: "Francia" },
  { code: "PT", flag: "🇵🇹", name_pt: "Portugal", name_en: "Portugal", name_es: "Portugal" },
  { code: "GB", flag: "🇬🇧", name_pt: "Reino Unido", name_en: "United Kingdom", name_es: "Reino Unido" },
  { code: "AR", flag: "🇦🇷", name_pt: "Argentina", name_en: "Argentina", name_es: "Argentina" },
  { code: "CL", flag: "🇨🇱", name_pt: "Chile", name_en: "Chile", name_es: "Chile" },
  { code: "CO", flag: "🇨🇴", name_pt: "Colômbia", name_en: "Colombia", name_es: "Colombia" },
  { code: "PE", flag: "🇵🇪", name_pt: "Peru", name_en: "Peru", name_es: "Perú" },
  { code: "CA", flag: "🇨🇦", name_pt: "Canadá", name_en: "Canada", name_es: "Canadá" },
  { code: "JP", flag: "🇯🇵", name_pt: "Japão", name_en: "Japan", name_es: "Japón" },
  { code: "KR", flag: "🇰🇷", name_pt: "Coreia do Sul", name_en: "South Korea", name_es: "Corea del Sur" },
  { code: "VN", flag: "🇻🇳", name_pt: "Vietnã", name_en: "Vietnam", name_es: "Vietnam" },
  { code: "TH", flag: "🇹🇭", name_pt: "Tailândia", name_en: "Thailand", name_es: "Tailandia" },
  { code: "IN", flag: "🇮🇳", name_pt: "Índia", name_en: "India", name_es: "India" },
  { code: "TR", flag: "🇹🇷", name_pt: "Turquia", name_en: "Turkey", name_es: "Turquía" },
  { code: "AE", flag: "🇦🇪", name_pt: "Emirados Árabes Unidos", name_en: "United Arab Emirates", name_es: "Emiratos Árabes Unidos" },
  { code: "PL", flag: "🇵🇱", name_pt: "Polônia", name_en: "Poland", name_es: "Polonia" },
  { code: "NL", flag: "🇳🇱", name_pt: "Holanda", name_en: "Netherlands", name_es: "Países Bajos" },
  { code: "BE", flag: "🇧🇪", name_pt: "Bélgica", name_en: "Belgium", name_es: "Bélgica" },
  { code: "SE", flag: "🇸🇪", name_pt: "Suécia", name_en: "Sweden", name_es: "Suecia" },
  { code: "CH", flag: "🇨🇭", name_pt: "Suíça", name_en: "Switzerland", name_es: "Suiza" },
  { code: "AT", flag: "🇦🇹", name_pt: "Áustria", name_en: "Austria", name_es: "Austria" },
  { code: "AU", flag: "🇦🇺", name_pt: "Austrália", name_en: "Australia", name_es: "Australia" },
  { code: "NZ", flag: "🇳🇿", name_pt: "Nova Zelândia", name_en: "New Zealand", name_es: "Nueva Zelanda" },
  { code: "ZA", flag: "🇿🇦", name_pt: "África do Sul", name_en: "South Africa", name_es: "Sudáfrica" },
  { code: "IE", flag: "🇮🇪", name_pt: "Irlanda", name_en: "Ireland", name_es: "Irlanda" },
  { code: "NO", flag: "🇳🇴", name_pt: "Noruega", name_en: "Norway", name_es: "Noruega" },
  { code: "DK", flag: "🇩🇰", name_pt: "Dinamarca", name_en: "Denmark", name_es: "Dinamarca" },
  { code: "FI", flag: "🇫🇮", name_pt: "Finlândia", name_en: "Finland", name_es: "Finlandia" },
  { code: "CZ", flag: "🇨🇿", name_pt: "República Tcheca", name_en: "Czech Republic", name_es: "República Checa" },
  { code: "GR", flag: "🇬🇷", name_pt: "Grécia", name_en: "Greece", name_es: "Grecia" },
  { code: "RO", flag: "🇷🇴", name_pt: "Romênia", name_en: "Romania", name_es: "Rumania" },
  { code: "HU", flag: "🇭🇺", name_pt: "Hungria", name_en: "Hungary", name_es: "Hungría" },
  { code: "IL", flag: "🇮🇱", name_pt: "Israel", name_en: "Israel", name_es: "Israel" },
  { code: "SG", flag: "🇸🇬", name_pt: "Singapura", name_en: "Singapore", name_es: "Singapur" },
  { code: "MY", flag: "🇲🇾", name_pt: "Malásia", name_en: "Malaysia", name_es: "Malasia" },
  { code: "ID", flag: "🇮🇩", name_pt: "Indonésia", name_en: "Indonesia", name_es: "Indonesia" },
  { code: "PH", flag: "🇵🇭", name_pt: "Filipinas", name_en: "Philippines", name_es: "Filipinas" },
  { code: "HK", flag: "🇭🇰", name_pt: "Hong Kong", name_en: "Hong Kong", name_es: "Hong Kong" },
  { code: "TW", flag: "🇹🇼", name_pt: "Taiwan", name_en: "Taiwan", name_es: "Taiwán" },
  { code: "EG", flag: "🇪🇬", name_pt: "Egito", name_en: "Egypt", name_es: "Egipto" },
  { code: "SA", flag: "🇸🇦", name_pt: "Arábia Saudita", name_en: "Saudi Arabia", name_es: "Arabia Saudita" },
  { code: "UY", flag: "🇺🇾", name_pt: "Uruguai", name_en: "Uruguay", name_es: "Uruguay" },
  { code: "PY", flag: "🇵🇾", name_pt: "Paraguai", name_en: "Paraguay", name_es: "Paraguay" },
  { code: "EC", flag: "🇪🇨", name_pt: "Equador", name_en: "Ecuador", name_es: "Ecuador" },
];
