project_id = "jnzamnnvzdecnnvvhzxn"

[functions.webhook-corvex]
verify_jwt = false

[functions.webhook-luna]
verify_jwt = false

[functions.webhook-vega]
verify_jwt = false

[functions.webhook-zedy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.rastreio-info]
verify_jwt = false

[functions.pagamento-info]
verify_jwt = false

[functions.save-push-subscription]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.webhook-blackcat]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.advance-shipments]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.falha-info]
enabled = true
verify_jwt = true
import_map = "./functions/falha-info/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/falha-info/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/falha-info/*.html" ]
