project_id = "jnzamnnvzdecnnvvhzxn"

[functions.webhook-corvex]
verify_jwt = false

[functions.webhook-luna]
verify_jwt = false

[functions.webhook-vega]
verify_jwt = false

[functions.webhook-zedy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.rastreio-info]
verify_jwt = false

[functions.pagamento-info]
verify_jwt = false

[functions.save-push-subscription]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.webhook-woovi]
verify_jwt = false

[functions.webhook-blackcat]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.advance-shipments]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.falha-info]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.auto-whatsapp-new-order]
verify_jwt = false

[functions.webhook-adoorei]
verify_jwt = false

[functions.resend-nfe]
verify_jwt = false

[functions.resend-daily-emails]
verify_jwt = false

[functions.redirect]
verify_jwt = false

[functions.api-external]
verify_jwt = false

[functions.webhook-recovery]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.webhook-nuvorafy]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.cron-check-pending-pix]
verify_jwt = false

[functions.retry-failed-sends]
verify_jwt = false
