import { useState, useCallback } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useLoja } from "@/contexts/LojaContext";
import { triggerNextEmail } from "@/lib/email-trigger";
import { fetchCep } from "@/lib/cep-utils";
import { Loader2, Plus, Trash2 } from "lucide-react";

const UF_OPTIONS = [
  "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA",
  "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO",
];

const steps = ["Dados do Cliente", "Endereço de Entrega", "Produtos & Fiscal"];

interface ProductItem {
  nome: string;
  quantidade: string;
  valor: string;
  cfop: string;
  ncm_sh: string;
  cst: string;
  unidade: string;
}

const emptyProduct = (): ProductItem => ({
  nome: "",
  quantidade: "1",
  valor: "",
  cfop: "",
  ncm_sh: "",
  cst: "",
  unidade: "UN",
});

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function NovoEnvioWizard({ open, onOpenChange }: Props) {
  const [step, setStep] = useState(0);
  const queryClient = useQueryClient();

  const [form, setForm] = useState({
    cliente_nome: "",
    cliente_cpf: "",
    cliente_email: "",
    cliente_telefone: "",
    cliente_cep: "",
    cliente_endereco: "",
    cliente_numero: "",
    cliente_bairro: "",
    cliente_cidade: "",
    cliente_estado: "",
    cliente_complemento: "",
  });

  const [products, setProducts] = useState<ProductItem[]>([emptyProduct()]);

  const { loja } = useLoja();
  const [buscandoCep, setBuscandoCep] = useState(false);

  const set = (key: string, val: string) => setForm((f) => ({ ...f, [key]: val }));

  const updateProduct = (index: number, key: keyof ProductItem, val: string) => {
    setProducts((prev) => {
      const copy = [...prev];
      copy[index] = { ...copy[index], [key]: val };
      return copy;
    });
  };

  const addProduct = () => {
    setProducts((prev) => [...prev, emptyProduct()]);
  };

  const removeProduct = (index: number) => {
    if (products.length <= 1) return;
    setProducts((prev) => prev.filter((_, i) => i !== index));
  };

  const handleCepBlur = useCallback(async () => {
    if (!form.cliente_cep || form.cliente_cep.replace(/\D/g, "").length !== 8) return;
    setBuscandoCep(true);
    const result = await fetchCep(form.cliente_cep);
    setBuscandoCep(false);
    if (result) {
      setForm((f) => ({
        ...f,
        cliente_endereco: result.logradouro || f.cliente_endereco,
        cliente_bairro: result.bairro || f.cliente_bairro,
        cliente_cidade: result.localidade || f.cliente_cidade,
        cliente_estado: result.uf || f.cliente_estado,
      }));
      toast.success("Endereço preenchido pelo CEP!");
    }
  }, [form.cliente_cep]);

  // Calculate totals
  const totalQty = products.reduce((sum, p) => sum + (parseInt(p.quantidade) || 0), 0);
  const totalValue = products.reduce((sum, p) => sum + (parseFloat(p.valor) || 0) * (parseInt(p.quantidade) || 1), 0);

  const createMutation = useMutation({
    mutationFn: async () => {
      if (!loja?.id) throw new Error("Loja não selecionada");

      // Buscar a empresa vinculada a esta loja
      const { data: empresa } = await supabase
        .from("empresas")
        .select("*")
        .eq("loja_id", loja.id)
        .maybeSingle();

      const { data: lojaData } = await supabase
        .from("lojas")
        .select("logistica_provider")
        .eq("id", loja.id)
        .single();

      const { data: configData } = await supabase
        .from("postagem_config")
        .select("template_ativo_id")
        .eq("loja_id", loja.id)
        .maybeSingle();

      // codigo_rastreio and transportadora are auto-generated by DB trigger

      // Build product data
      // If single product, store as plain string (backwards compatible)
      // If multiple products, store as JSON array in the produto field
      let produtoField: string;
      let quantidade: number;
      let valor: number;
      let cfop: string | null = null;
      let ncm_sh: string | null = null;
      let cst: string | null = null;
      let unidade: string = "UN";

      if (products.length === 1) {
        const p = products[0];
        produtoField = p.nome;
        quantidade = parseInt(p.quantidade) || 1;
        valor = parseFloat(p.valor) || 0;
        cfop = p.cfop || null;
        ncm_sh = p.ncm_sh || null;
        cst = p.cst || null;
        unidade = p.unidade || "UN";
      } else {
        // Multiple products — serialize as JSON string in the produto field
        const items = products.map((p, idx) => ({
          codigo: idx + 1,
          nome: p.nome,
          quantidade: parseInt(p.quantidade) || 1,
          valor: parseFloat(p.valor) || 0,
          cfop: p.cfop || null,
          ncm_sh: p.ncm_sh || null,
          cst: p.cst || null,
          unidade: p.unidade || "UN",
        }));
        produtoField = JSON.stringify(items);
        quantidade = totalQty;
        valor = totalValue;
        // Use first product's fiscal data as defaults
        cfop = products[0].cfop || null;
        ncm_sh = products[0].ncm_sh || null;
        cst = products[0].cst || null;
        unidade = products[0].unidade || "UN";
      }

      const { data: newEnvio, error } = await supabase.from("envios").insert({
        loja_id: loja.id,
        empresa_id: empresa?.id || null,
        cliente_nome: form.cliente_nome,
        cliente_email: form.cliente_email,
        cliente_cpf: form.cliente_cpf || null,
        cliente_telefone: form.cliente_telefone || null,
        cliente_cep: form.cliente_cep || null,
        cliente_endereco: form.cliente_endereco || null,
        cliente_numero: form.cliente_numero || null,
        cliente_bairro: form.cliente_bairro || null,
        cliente_cidade: form.cliente_cidade || null,
        cliente_estado: form.cliente_estado || null,
        cliente_complemento: form.cliente_complemento || null,
        // codigo_rastreio and transportadora auto-generated by DB trigger
        produto: produtoField,
        valor,
        quantidade,
        cfop,
        ncm_sh,
        cst,
        unidade,
        postagem_template_id: configData?.template_ativo_id || null,
        status: "pendente"
      } as any).select().single();

      if (error) throw error;

      // Email será disparado apenas quando o usuário avançar o status manualmente
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["envios"] });
      resetAndClose();
      toast.success("Pedido salvo com sucesso!");
    },
    onError: (error: any) => {
      console.error("Erro ao salvar envio:", error);
      toast.error(error.message || "Erro ao salvar pedido.");
    },
  });

  const resetAndClose = () => {
    setStep(0);
    setForm({
      cliente_nome: "", cliente_cpf: "", cliente_email: "", cliente_telefone: "",
      cliente_cep: "", cliente_endereco: "", cliente_numero: "", cliente_bairro: "",
      cliente_cidade: "", cliente_estado: "", cliente_complemento: "",
    });
    setProducts([emptyProduct()]);
    onOpenChange(false);
  };

  const canNext = () => {
    if (step === 0) return !!form.cliente_nome && !!form.cliente_email;
    if (step === 1) return !!form.cliente_cep && !!form.cliente_endereco && !!form.cliente_cidade && !!form.cliente_estado;
    // Step 2: need at least one product with name and value
    return products.every((p) => !!p.nome && !!p.valor);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Novo Envio</DialogTitle>
        </DialogHeader>

        {/* Step indicator */}
        <div className="flex items-center justify-center gap-2 py-2">
          {steps.map((s, i) => (
            <div key={s} className="flex items-center gap-2">
              <div
                className={`h-8 w-8 rounded-full flex items-center justify-center text-xs font-bold transition-colors ${i <= step
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-muted-foreground"
                  }`}
              >
                {i + 1}
              </div>
              {i < steps.length - 1 && (
                <div className={`w-8 h-0.5 ${i < step ? "bg-primary" : "bg-muted"}`} />
              )}
            </div>
          ))}
        </div>
        <p className="text-center text-sm font-medium text-foreground">{steps[step]}</p>

        {/* Step 1 */}
        {step === 0 && (
          <div className="space-y-3 mt-2">
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">Nome *</Label>
                <Input value={form.cliente_nome} onChange={(e) => set("cliente_nome", e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">CPF</Label>
                <Input value={form.cliente_cpf} onChange={(e) => set("cliente_cpf", e.target.value)} placeholder="Opcional" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">Email *</Label>
                <Input type="email" value={form.cliente_email} onChange={(e) => set("cliente_email", e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Telefone</Label>
                <Input value={form.cliente_telefone} onChange={(e) => set("cliente_telefone", e.target.value)} placeholder="Opcional" />
              </div>
            </div>
          </div>
        )}

        {/* Step 2 */}
        {step === 1 && (
          <div className="space-y-3 mt-2">
            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">CEP *</Label>
                <div className="relative">
                  <Input value={form.cliente_cep} onChange={(e) => set("cliente_cep", e.target.value)} onBlur={handleCepBlur} />
                  {buscandoCep && <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 animate-spin text-muted-foreground" />}
                </div>
              </div>
              <div className="col-span-2 space-y-1">
                <Label className="text-xs">Endereço *</Label>
                <Input value={form.cliente_endereco} onChange={(e) => set("cliente_endereco", e.target.value)} />
              </div>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">Número *</Label>
                <Input value={form.cliente_numero} onChange={(e) => set("cliente_numero", e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Bairro *</Label>
                <Input value={form.cliente_bairro} onChange={(e) => set("cliente_bairro", e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Complemento</Label>
                <Input value={form.cliente_complemento} onChange={(e) => set("cliente_complemento", e.target.value)} />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">Cidade *</Label>
                <Input value={form.cliente_cidade} onChange={(e) => set("cliente_cidade", e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">UF *</Label>
                <Select value={form.cliente_estado} onValueChange={(v) => set("cliente_estado", v)}>
                  <SelectTrigger><SelectValue placeholder="UF" /></SelectTrigger>
                  <SelectContent>
                    {UF_OPTIONS.map((uf) => (
                      <SelectItem key={uf} value={uf}>{uf}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
        )}

        {/* Step 3 - Products */}
        {step === 2 && (
          <div className="space-y-3 mt-2">
            {products.map((product, idx) => (
              <div key={idx} className="border rounded-lg p-3 space-y-2 relative bg-muted/20">
                {/* Product header */}
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-muted-foreground">
                    Produto {idx + 1}
                  </span>
                  {products.length > 1 && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 w-6 p-0 text-destructive hover:text-destructive"
                      onClick={() => removeProduct(idx)}
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  )}
                </div>

                <div className="grid grid-cols-4 gap-2">
                  <div className="col-span-2 space-y-1">
                    <Label className="text-xs">Nome do Produto *</Label>
                    <Input
                      value={product.nome}
                      onChange={(e) => updateProduct(idx, "nome", e.target.value)}
                      placeholder="Ex: Camiseta P"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">Qtd</Label>
                    <Input
                      type="number"
                      min="1"
                      value={product.quantidade}
                      onChange={(e) => updateProduct(idx, "quantidade", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">Preço (R$) *</Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={product.valor}
                      onChange={(e) => updateProduct(idx, "valor", e.target.value)}
                    />
                  </div>
                </div>

                {/* Fiscal data (collapsible) */}
                <div className="grid grid-cols-4 gap-2">
                  <div className="space-y-1">
                    <Label className="text-[10px] text-muted-foreground">CFOP</Label>
                    <Input
                      className="h-7 text-xs"
                      value={product.cfop}
                      onChange={(e) => updateProduct(idx, "cfop", e.target.value)}
                      placeholder="5102"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-[10px] text-muted-foreground">NCM/SH</Label>
                    <Input
                      className="h-7 text-xs"
                      value={product.ncm_sh}
                      onChange={(e) => updateProduct(idx, "ncm_sh", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-[10px] text-muted-foreground">CST</Label>
                    <Input
                      className="h-7 text-xs"
                      value={product.cst}
                      onChange={(e) => updateProduct(idx, "cst", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-[10px] text-muted-foreground">Unidade</Label>
                    <Input
                      className="h-7 text-xs"
                      value={product.unidade}
                      onChange={(e) => updateProduct(idx, "unidade", e.target.value)}
                    />
                  </div>
                </div>
              </div>
            ))}

            {/* Add product button */}
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="w-full border-dashed"
              onClick={addProduct}
            >
              <Plus className="h-3.5 w-3.5 mr-1" />
              Adicionar mais um produto
            </Button>

            {/* Totals */}
            {products.length > 0 && (
              <div className="flex items-center justify-between text-sm bg-muted/40 rounded-lg px-3 py-2 mt-2">
                <span className="text-muted-foreground">
                  {products.length} produto(s) · {totalQty} unidade(s)
                </span>
                <span className="font-bold">
                  Total: {totalValue.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                </span>
              </div>
            )}
          </div>
        )}

        {/* Navigation */}
        <div className="flex justify-between mt-4">
          <Button variant="outline" onClick={() => (step === 0 ? onOpenChange(false) : setStep(step - 1))}>
            {step === 0 ? "Cancelar" : "Voltar"}
          </Button>
          {step < 2 ? (
            <Button onClick={() => setStep(step + 1)} disabled={!canNext()}>
              Próximo
            </Button>
          ) : (
            <Button onClick={() => createMutation.mutate()} disabled={!canNext() || createMutation.isPending}>
              {createMutation.isPending ? "Salvando..." : "Salvar Pedido"}
            </Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
