
-- 1) Table
CREATE TABLE public.global_flow_system_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  step_order int NOT NULL CHECK (step_order BETWEEN 1 AND 10),
  lang text NOT NULL CHECK (lang IN ('en','es')),
  step_key text NOT NULL,
  status_label text NOT NULL,
  subject text NOT NULL,
  preview text NOT NULL,
  headline text NOT NULL,
  intro text NOT NULL,
  body text NOT NULL,
  hint text,
  cta_label text NOT NULL,
  closing text NOT NULL,
  sms_texto text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(step_order, lang)
);

GRANT SELECT ON public.global_flow_system_templates TO anon, authenticated;
GRANT ALL    ON public.global_flow_system_templates TO service_role;

ALTER TABLE public.global_flow_system_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "read system global templates"
  ON public.global_flow_system_templates
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "admin manage system global templates"
  ON public.global_flow_system_templates
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TRIGGER trg_global_flow_system_templates_updated_at
  BEFORE UPDATE ON public.global_flow_system_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 2) Seed EN
INSERT INTO public.global_flow_system_templates
(step_order, lang, step_key, status_label, subject, preview, headline, intro, body, hint, cta_label, closing, sms_texto) VALUES
(1,'en','order_received','Order Received',
 'Order received — we''re getting it ready',
 'Thanks {{name}}! Your order from {{empresa}} is confirmed.',
 'Order received 🎉',
 'Hi {{name}}, thanks for shopping with {{empresa}}!',
 'We''ve just received your order and our team is already starting to prepare it. You''ll get an update at every step — from the warehouse all the way to your door.',
 'Average international delivery: 12–25 business days.',
 'Track my order','Welcome aboard,',
 '{{name}}, we received your order at {{empresa}}. Track: {{link}}'),
(2,'en','order_prepared','Order Prepared',
 'Your order is packed and ready to ship',
 'Good news {{name}} — packing is done.',
 'Order prepared 📦',
 'Hi {{name}}, quick update from {{empresa}}.',
 'Your items have been carefully checked, packed and labeled. The package is now in the queue to be picked up by our international carrier.',
 'Next step: handover to the shipping carrier.',
 'Track my order','Talk soon,',
 '{{name}}, your order is packed and ready to ship. {{link}}'),
(3,'en','shipped_by_sender','Shipped by Sender',
 'Shipped! Your order is on its way',
 '{{name}}, your package just left our warehouse.',
 'Shipped 🚚',
 'Great news {{name}} — your order has been shipped!',
 'Your package has been handed over to the carrier in {{originCountry}}. Tracking events will start appearing shortly. Your tracking code is {{tracking}}.',
 'It can take 24–48h for the first scan to appear.',
 'See live tracking','Safe travels to your package,',
 '{{name}}, your order has been shipped! Track: {{link}}'),
(4,'en','left_origin','Left Country of Origin',
 'Your package left {{originCountry}}',
 'International journey started.',
 'Left country of origin ✈️',
 'Hi {{name}}, your package is officially traveling internationally.',
 'It has departed from {{originCountry}} and is now heading to your destination country. This is usually the longest leg of the trip, but every scan brings it closer.',
 NULL,
 'Track my order','We''ll keep you posted,',
 '{{name}}, your package left {{originCountry}}. {{link}}'),
(5,'en','international_transit','In International Transit',
 'In international transit',
 '{{name}}, your package is crossing borders.',
 'In international transit 🌍',
 'Hi {{name}}, your order is currently in international transit.',
 'Updates can be less frequent during this stage — that''s normal for international freight. As soon as it arrives in your country, you''ll get a new notification.',
 'No action needed from you right now.',
 'Check status','Thanks for your patience,',
 '{{name}}, your order is in international transit. {{link}}'),
(6,'en','arrived_destination','Arrived at Destination Country',
 'Arrived in your country 🛬',
 'Almost there, {{name}}.',
 'Arrived at destination country',
 'Great news {{name}} — your package just landed in your country!',
 'It will now be transferred to customs for inspection and clearance before being released to the local carrier.',
 'Customs clearance usually takes 1–5 business days.',
 'Track my order','Getting closer,',
 '{{name}}, your package arrived in your country! {{link}}'),
(7,'en','customs','In Customs Processing',
 'In customs processing',
 'Your package is going through customs.',
 'In customs processing 🛃',
 'Hi {{name}}, a quick status update.',
 'Your package is currently being processed by customs. This is a standard step for every international shipment and no action is required from you.',
 'We''ll notify you as soon as it''s released.',
 'Track my order','Hang tight,',
 '{{name}}, your package is in customs. No action needed. {{link}}'),
(8,'en','local_transit','In Local Transit',
 'Released — now in local transit',
 'Cleared customs, on the way to your city.',
 'In local transit 🚛',
 'Hi {{name}}, your package cleared customs!',
 'It''s now traveling through the local network and heading to the distribution center closest to your address.',
 NULL,
 'Track my order','Almost there,',
 '{{name}}, cleared customs! Now in local transit. {{link}}'),
(9,'en','out_for_delivery','Out for Delivery',
 '📍 Out for delivery — arriving today!',
 '{{name}}, your package is on the delivery truck.',
 'Out for delivery',
 'Hi {{name}}, exciting update!',
 'Your package is loaded on the delivery vehicle and is scheduled to arrive today.',
 'Please make sure someone is available at the address to receive it.',
 'Track in real time','See you in a few hours,',
 '{{name}}, OUT FOR DELIVERY today. Please be available. {{link}}'),
(10,'en','delivered','Delivered',
 'Delivered ✅ Thanks for choosing {{empresa}}!',
 'Your order has been delivered.',
 'Delivered',
 'Hi {{name}}, your order has been delivered!',
 'We hope you love it. If anything is wrong with your order, just reply to this email and we''ll make it right.',
 'Would you mind sharing a quick review? It really helps us.',
 'View order','Thanks for shopping with us,',
 '{{name}}, your order has been delivered. Thank you! {{link}}');

-- Seed ES
INSERT INTO public.global_flow_system_templates
(step_order, lang, step_key, status_label, subject, preview, headline, intro, body, hint, cta_label, closing, sms_texto) VALUES
(1,'es','order_received','Pedido Recibido',
 'Pedido recibido — lo estamos preparando',
 'Gracias {{name}}! Tu pedido en {{empresa}} fue confirmado.',
 'Pedido recibido 🎉',
 'Hola {{name}}, ¡gracias por tu compra en {{empresa}}!',
 'Acabamos de recibir tu pedido y nuestro equipo ya está empezando a prepararlo. Te avisaremos en cada etapa — desde el almacén hasta tu puerta.',
 'Tiempo promedio de entrega internacional: 12–25 días hábiles.',
 'Rastrear pedido','Bienvenido,',
 '{{name}}, recibimos tu pedido en {{empresa}}. Rastrear: {{link}}'),
(2,'es','order_prepared','Pedido Preparado',
 'Tu pedido está empacado y listo para enviar',
 'Buenas noticias {{name}} — empacado terminado.',
 'Pedido preparado 📦',
 'Hola {{name}}, una actualización rápida de {{empresa}}.',
 'Tus artículos fueron revisados, empacados y etiquetados con cuidado. El paquete ya está en la cola para ser recogido por nuestro transportista internacional.',
 'Próximo paso: entrega al transportista.',
 'Rastrear pedido','Hablamos pronto,',
 '{{name}}, tu pedido fue empacado y está listo para enviar. {{link}}'),
(3,'es','shipped_by_sender','Enviado por el Remitente',
 '¡Enviado! Tu pedido va en camino',
 '{{name}}, tu paquete acaba de salir de nuestro almacén.',
 'Enviado 🚚',
 '¡Buenas noticias {{name}} — tu pedido fue enviado!',
 'Tu paquete fue entregado al transportista en {{originCountry}}. Los eventos de rastreo comenzarán a aparecer pronto. Tu código de rastreo es {{tracking}}.',
 'Puede tardar 24–48h hasta el primer escaneo.',
 'Ver rastreo en vivo','Buen viaje a tu paquete,',
 '{{name}}, tu pedido fue enviado! Rastrear: {{link}}'),
(4,'es','left_origin','Salió del País de Origen',
 'Tu paquete salió de {{originCountry}}',
 'Comenzó el viaje internacional.',
 'Salió del país de origen ✈️',
 'Hola {{name}}, tu paquete está oficialmente viajando internacionalmente.',
 'Salió de {{originCountry}} y se dirige a tu país de destino. Suele ser el tramo más largo del viaje, pero cada escaneo lo acerca más.',
 NULL,
 'Rastrear pedido','Te mantendremos al tanto,',
 '{{name}}, tu paquete salió de {{originCountry}}. {{link}}'),
(5,'es','international_transit','En Tránsito Internacional',
 'En tránsito internacional',
 '{{name}}, tu paquete está cruzando fronteras.',
 'En tránsito internacional 🌍',
 'Hola {{name}}, tu pedido está actualmente en tránsito internacional.',
 'Las actualizaciones pueden ser menos frecuentes en esta etapa — es normal en envíos internacionales. Apenas llegue a tu país, recibirás una nueva notificación.',
 'No necesitas hacer nada por ahora.',
 'Ver estado','Gracias por tu paciencia,',
 '{{name}}, tu pedido está en tránsito internacional. {{link}}'),
(6,'es','arrived_destination','Llegó al País de Destino',
 'Llegó a tu país 🛬',
 'Ya casi, {{name}}.',
 'Llegó al país de destino',
 'Buenas noticias {{name}} — ¡tu paquete acaba de llegar a tu país!',
 'Ahora será transferido a la aduana para inspección y liberación antes de ser entregado al transportista local.',
 'El proceso aduanero suele tardar 1–5 días hábiles.',
 'Rastrear pedido','Cada vez más cerca,',
 '{{name}}, tu paquete llegó a tu país! {{link}}'),
(7,'es','customs','En Procesamiento Aduanero',
 'En procesamiento aduanero',
 'Tu paquete está pasando por la aduana.',
 'En procesamiento aduanero 🛃',
 'Hola {{name}}, una actualización rápida.',
 'Tu paquete está siendo procesado por la aduana. Es un paso estándar para todo envío internacional y no necesitas hacer nada.',
 'Te avisaremos apenas sea liberado.',
 'Rastrear pedido','Tranquilo,',
 '{{name}}, tu paquete está en aduana. Sin acción necesaria. {{link}}'),
(8,'es','local_transit','En Tránsito Local',
 'Liberado — ahora en tránsito local',
 'Liberado de la aduana, en camino a tu ciudad.',
 'En tránsito local 🚛',
 'Hola {{name}}, ¡tu paquete fue liberado de la aduana!',
 'Ya está viajando por la red local hacia el centro de distribución más cercano a tu dirección.',
 NULL,
 'Rastrear pedido','Ya casi,',
 '{{name}}, liberado de la aduana! En tránsito local. {{link}}'),
(9,'es','out_for_delivery','Salió para Entrega',
 '📍 Salió para entrega — ¡llega hoy!',
 '{{name}}, tu paquete está en el camión de entrega.',
 'Salió para entrega',
 'Hola {{name}}, ¡actualización importante!',
 'Tu paquete está cargado en el vehículo de entrega y está programado para llegar hoy.',
 'Por favor asegúrate de que haya alguien disponible para recibirlo.',
 'Rastrear en tiempo real','Nos vemos en unas horas,',
 '{{name}}, SALIO PARA ENTREGA hoy. Por favor disponible. {{link}}'),
(10,'es','delivered','Entregado',
 'Entregado ✅ ¡Gracias por elegir {{empresa}}!',
 'Tu pedido fue entregado.',
 'Entregado',
 'Hola {{name}}, ¡tu pedido fue entregado!',
 'Esperamos que te encante. Si algo no está bien con tu pedido, solo responde a este email y lo resolveremos.',
 '¿Nos dejarías una reseña rápida? Nos ayuda mucho.',
 'Ver pedido','Gracias por tu compra,',
 '{{name}}, tu pedido fue entregado. Gracias! {{link}}');

-- 3) Backfill: align language of in-progress international shipments with current store config
UPDATE public.envios e
SET global_flow_lang = c.idioma
FROM public.global_flow_config c
WHERE e.loja_id = c.loja_id
  AND e.is_international = true
  AND COALESCE(e.ultimo_evento_ordem, 0) <= 1
  AND COALESCE(e.global_flow_lang, '') <> c.idioma
  AND c.idioma IN ('en','es');
